<a href="https://colab.research.google.com/github/Asami1997/Applied-Data-Science-Specialization-The-University-of-Michigan/blob/master/Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
def addNumbers(x,y):
  return x+y

In [0]:
addNumbers(2,3)

5

In [0]:
def addNumbersOptional(x, y, z = None):
  if (z == None):
    return x+y
  else:
    return x+y+z

In [0]:
addNumbersOptional(1,2,3)

6

In [0]:
addNumbersOptional(3,3)

6

In [0]:
def addNumbersOverLoaded(x, y, kind='sub'):
  if (kind == 'add'):
    return x+y
  else:
    return x-y

addNumbersOverLoaded(3,4,kind = 'add')

7

In [0]:
type('this is a string')

str

In [0]:
x = (1,1.3,'string')

In [0]:
x

(1, 1.3, 'string')

In [0]:
y = [1,'string',2]

In [0]:
y

[1, 'string', 2]

In [0]:
y.append(3)

In [0]:
y

[1, 'string', 2, 3]

In [0]:
y[4]

IndexError: ignored

In [0]:
y[2]

2

In [0]:
y[2] = 4

In [0]:
y

[1, 'string', 4, 3]

In [0]:
for item in y:
  print(item)

1
string
4
3


concatinating lists

In [0]:
[1,2,3,4] + [5,6,6,8]

[1, 2, 3, 4, 5, 6, 6, 8]

Repeating a value

In [13]:
[3] * 2

[3, 3]



```
# This is formatted as code
```

Check for set membership ( returns boolean )

In [0]:
1 in [1,3,4,5]

True

Slicing

In [0]:
x = [1,2,3,4,5]

In [0]:
x[1:2]

[2]

In [0]:
x[2:]

[3, 4, 5]

In [0]:
x[2:5]

[3, 4, 5]

In [0]:
x[2:4]

[3, 4]

In [0]:
x[2:6]

[3, 4, 5]

In [0]:
firstName = "Ahmad"
lastName  = "Hussein"
fullName = firstName + lastName

In [0]:
fullName

'AhmadHussein'

In [0]:
firstName * 5

'AhmadAhmadAhmadAhmadAhmad'

Split on white spaces then return the first element in the new list

In [0]:
firstName = "Ahmad Sami Hussein".split(" ")[0]
firstName

'Ahmad'

In [0]:
dictionary1 = {'name' : "ahmad","sami" : "sami@gmail.com"}

In [16]:
dictionary1[0]

KeyError: ignored

In [0]:
emailsDictionary = {'Ahmad' : "asami1997@gmaill.com", 'Jhon' : "jhon@gmail.com"}

In [0]:
emailsDictionary['Ahmad']

'asami1997@gmaill.com'

In [0]:
for key in emailsDictionary.keys():
  print(key)

Ahmad
Jhon


In [0]:
for name,email in emailsDictionary.items():
  print(name)
  print(email)

Ahmad
asami1997@gmaill.com
Jhon
jhon@gmail.com


In [0]:
x = ("Ahmad","Hussein","asami1997@gmail.com")

Unpacking the tuple through assignment

In [0]:
firstName,lastName,email = x

In [0]:
firstName

'Ahmad'

In [0]:
email

'asami1997@gmail.com'

In [0]:
z = "{} example of string substitution"
z.format("this is")

'this is example of string substitution'

In [0]:
s = " i am {0:0.2f}% sure of that"
s.format(100)

' i am 100.00% sure of that'

In [19]:
testString = "this is a {first:0.3f} precision"
testString.format(first = 4.987676373)

'this is a 4.988 precision'

In [17]:
s = " i am {key:0.2f}% sure of that"
s.format(key = 100)

' i am 100.00% sure of that'

Setting the floating point precision value in the notebook using the precision magic command

In [21]:
%precision %.2f

'%.2f'

Opening a csv file, reading it as dictionary and then adding all the 

dictionaries as a list in which each dictionary in a list is a sample.


In [0]:
import csv

In [0]:
with open('car_data.csv') as csvFile:
  carList = list(csv.DictReader(csvFile))
carList[:3]

[OrderedDict([('', '1'),
              ('make', 'alfa-romero'),
              ('fuel_type', 'gas'),
              ('aspiration', 'std'),
              ('num_of_doors', 'two'),
              ('body_style', 'convertible'),
              ('drive_wheels', 'rwd'),
              ('engine_location', 'front'),
              ('wheel_base', '88.6'),
              ('length', '168.8'),
              ('width', '64.1'),
              ('height', '48.8'),
              ('curb_weight', '2548'),
              ('engine_type', 'dohc'),
              ('num_of_cylinders', 'four'),
              ('engine_size', '130'),
              ('fuel_system', 'mpfi'),
              ('compression_ratio', '9'),
              ('horsepower', '111'),
              ('peak_rpm', '5000'),
              ('city_mpg', '21'),
              ('highway_mpg', '27'),
              ('price', '13495')]),
 OrderedDict([('', '2'),
              ('make', 'alfa-romero'),
              ('fuel_type', 'gas'),
              ('aspiration', 'std')

In [0]:
len(carList)

205

In [0]:
carList[0].keys()

odict_keys(['', 'make', 'fuel_type', 'aspiration', 'num_of_doors', 'body_style', 'drive_wheels', 'engine_location', 'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type', 'num_of_cylinders', 'engine_size', 'fuel_system', 'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg', 'highway_mpg', 'price'])

In [0]:
carList[0].values()

odict_values(['1', 'alfa-romero', 'gas', 'std', 'two', 'convertible', 'rwd', 'front', '88.6', '168.8', '64.1', '48.8', '2548', 'dohc', 'four', '130', 'mpfi', '9', '111', '5000', '21', '27', '13495'])

simpilfied loop , the value of every iteration is added. Loops throught the list of dictionaries and adds up the city_mpg. converts the value to int

In [0]:
sum(int(car['city_mpg']) for car in carList)

5170

The set function function returns a list of unique values. The function below will return a set of all the fuel types in our list of dictionaries


In [0]:
set(car['fuel_type'] for car in carList)

{'diesel', 'gas'}

In [0]:
import time

UNIX TimeStamp

In [0]:
time.time()

1587153331.17

converting the runnting total seconds to a timestamp

In [0]:
import datetime as dt

In [0]:
timestamp = dt.datetime.fromtimestamp(time.time())

In [0]:
timestamp.year

2020

In [0]:
class testCalss:
  #instance variables
  brand = "Nike"

  def changeBrandName(self,name):
    self.brand = name

Some functional programming concepts in python, Map function (Higher Order Functions)

In [0]:
People = ['Ahmad Sami','Arnold Schwarzenegger']

def split_name(name):
  firstName = name.split(' ')[0]
  lastName - name.split(' ')[-1]
  
  return '{} {}'.format(firstName,lastName)

map(split_name,People)

Lambda Functions. Structute : Keyword Lambda followed by the list of argument, colon , then the expression.

In [0]:
my_function = lambda a,b,c : a + b + c

In [0]:
my_function

<function __main__.<lambda>>

In [0]:
my_function()

TypeError: ignored

In [0]:
my_function(1,2,3)

6

List Comprehensions, structure : value you want to insert , loop , then condition

> Indented block



In [0]:
my_list = [number for number in range(4) if number == 3]

In [34]:
my_list

[3]

Nested for loop in list comprehension


In [0]:
times_tables = [i*j for i in range(10) for j in range(10)]

In [0]:
times_tables

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 0,
 4,
 8,
 12,
 16,
 20,
 24,
 28,
 32,
 36,
 0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 0,
 6,
 12,
 18,
 24,
 30,
 36,
 42,
 48,
 54,
 0,
 7,
 14,
 21,
 28,
 35,
 42,
 49,
 56,
 63,
 0,
 8,
 16,
 24,
 32,
 40,
 48,
 56,
 64,
 72,
 0,
 9,
 18,
 27,
 36,
 45,
 54,
 63,
 72,
 81]

Numpy Arrays



In [0]:
import numpy as np

In [0]:
array_1 = np.array([1,2,3])

In [0]:
array_1

array([1, 2, 3])

Multidimensional Arrays (Matrices)

In [0]:
Two_dimensional_Array = np.array([[1,2,3,4],[5,6,7,8]])

In [0]:
Two_dimensional_Array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Array from 5 to 30 with intervals of 5

In [0]:
n = np.arange(5,30,5)

In [0]:
n

array([ 5, 10, 15, 20, 25])

reshape to 3 by 5 array

In [0]:
n.reshape(2,3)

ValueError: ignored

In [0]:
np.ones(1,2)

TypeError: ignored

In [0]:
np.ones((1,3))

array([[1., 1., 1.]])

In [0]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

returns ones in the diagonal and zeros everywhere

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.vstack(([1,2,3],[3,6,7]))

array([[1, 2, 3],
       [3, 6, 7]])

In [0]:
y = np.array([1,2,3])

In [0]:
y**2

array([1, 4, 9])

In [0]:
np.array([y,y**2])

array([[1, 2, 3],
       [1, 4, 9]])

Transpose an array

In [0]:
x = np.array(([1,2,3,4],[4,5,6,7]))

In [0]:
x

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [0]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [0]:
x.dtype

dtype('int64')

In [0]:
x.type()

AttributeError: ignored

In [0]:
type(x)

numpy.ndarray

In [0]:
x.sum()

32

In [0]:
x.max()

7

In [0]:
x.min()

1

cast the data of an array to float


In [37]:
x.astype('f')

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]], dtype=float32)

find the index of the largest value

In [0]:
x.argmax()

7

indexing and slicing


In [0]:
k = np.arange(30) ** 2

In [39]:
k

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [0]:
k[0]

0

In [0]:
k[22]

484

In [0]:
k[0:5]

array([ 0,  1,  4,  9, 16])

In [0]:
k[-4:]

array([676, 729, 784, 841])

Getting values from 1 tell 10 and counting forward by two

In [41]:
k[1:10:2]

array([ 1,  9, 25, 49, 81])

In [0]:
p = np.arange(36)

In [44]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [0]:
p.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [0]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [0]:
p.resize(6,6)

In [59]:
p.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [58]:
p[::7]

array([[0, 1, 2, 3, 4, 5]])

Indexing MultiDimensional arrays , second row from 3 to 5

In [0]:
p[2,3:5]

array([15, 16])

p2 here is referencing p



In [0]:
p2 = p[3,2:6]

In [0]:
p2

array([20, 21, 22, 23])

In [0]:
p2[:] = 0

In [0]:
p

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19,  0,  0,  0,  0],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [0]:
p3 = p.copy()

Iterating through arrays

Generate a numpy array of random inetegrs. Structure : (From , To , shape)

In [0]:
randomArray = np.random.randint(1,20,(3,3))

In [4]:
randomArray

array([[ 3, 18, 18],
       [ 2,  6, 14],
       [11, 19, 19]])

Iterate through the rows

In [6]:
for row in randomArray:
  print(row)


[ 3 18 18]
[ 2  6 14]
[11 19 19]


iterating using the index, RANGE function will ny defualt start from zero to the specified index

In [7]:
for i in range(len(randomArray)):
  print(randomArray[i])


[ 3 18 18]
[ 2  6 14]
[11 19 19]


the enumerate function iterates through both the index and the row

In [9]:
for i,row in enumerate(randomArray):
  print("row {} is  {}".format(i,row))

row 0 is  [ 3 18 18]
row 1 is  [ 2  6 14]
row 2 is  [11 19 19]


iterating through multiple arrays at once

In [0]:
array2 = np.random.randint(2,8,(3,3))

In [11]:
for i,j in zip(randomArray,array2):
  print(i,j)

[ 3 18 18] [6 3 4]
[ 2  6 14] [7 4 7]
[11 19 19] [3 6 7]


In [42]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]